export enum HttpPathItem {
    Accept = 'accept',
    Api = 'api',
    Apply = 'apply',
    Check = 'check',
    Deny = 'deny',
    Disable = 'disable',
    Download = 'download',
    Edit = 'edit',
    Enable = 'enable',
    File = 'file',
    Notification = 'notification',
    Password = 'password',
    Query = 'query',
    Read = 'read',
    Remove = 'remove',
    Result = 'result',
    Session = 'session',
    Task = 'task',
    Template = 'template',
    User = 'user',
}
