export enum HttpPathItem {
    ACCEPT = 'accept',
    API = 'api',
    APPLY = 'apply',
    CHECK = 'check',
    DENY = 'deny',
    DISABLE = 'disable',
    DOWNLOAD = 'download',
    EDIT = 'edit',
    ENABLE = 'enable',
    FILE = 'file',
    PASSWORD = 'password',
    QUERY = 'query',
    REMOVE = 'remove',
    SESSION = 'session',
    TASK = 'task',
    TEMPLATE = 'template',
    USER = 'user',
}
